# Generated by Django 5.0.7 on 2024-07-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirosta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.IntegerField(default=0, verbose_name='좋아요 개수'),
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
