# Generated by Django 5.0.7 on 2024-07-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to='ideas/%Y%m%d', verbose_name='이미지')),
                ('content', models.TextField(verbose_name='설명')),
                ('interest', models.IntegerField(verbose_name='관심도')),
                ('devtool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devtools.devtool', verbose_name='개발도구')),
            ],
        ),
    ]
