# Generated by Django 5.0.7 on 2024-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=20)),
                ('actor', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('액션', '액션 영화'), ('범죄', '범죄 영화'), ('SF', 'SF 영화'), ('코미디', '코미디 영화'), ('로맨스', '로맨스 영화'), ('스릴러', '스릴러 영화'), ('공포', '공포 영화'), ('판타지', '판타지 영화'), ('멜로', '멜로 영화'), ('스포츠', '스포츠 영화'), ('뮤지컬', '뮤지컬 영화'), ('음악', '음악 영화')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('running_time', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
